cask_args appdir: "/Applications"

tap "homebrew/core"
tap "homebrew/versions"
tap "homebrew/bundle"
tap "caskroom/fonts"
tap "caskroom/cask"

brew "curl"
brew "git"
brew "rsync"
brew "tree"
brew "vim"
brew "wget"

brew "sqlite"
brew "unixodbc"

cask "caskroom/fonts/font-source-code-pro"
cask "caskroom/fonts/font-hack-nerd-font"
cask "iterm2"

cask "virtualbox"
cask "vagrant"

cask "vlc"
cask "ccleaner"

cask "textmate"

# Paid
# cask "ngrok"
# cask "bartender"
cask "little-snitch"
# cask "micro-snitch"

# cask "dash3"


# App Store
# cask "the-unarchiver"

# App Store
# cask "screenflick"
# cask "daisydisk"